### ISSUE TITLE
React Native conversion

### ISSUE THREAD

**Issue by mtwallet** [icsfl/cordova-honeywell#2]
@brendonparker Do you have any experience of React Native. I am trying to convert what you have done here but I am struggling with the implementation.

**Comment by brendonparker** [comment]
Sorry - I don't have any experience using React Native. Did you try [React-Native Cordova Plugin Adapter](https://github.com/axemclion/react-native-cordova-plugin)?

**Comment by mtwallet** [comment]
@brendonparker no worries it was a long shot. Unfortunately the plugin you suggest no longer works with the current version of React Native. Thanks for your help anyway.

**Comment by brendonparker** [comment]
Ok. Closing this as it is outside the scope of this repo.
